### ISSUE TITLE
Migrer le projet en TypeScript et Node

### ISSUE THREAD

**Issue by Kocal** [YaourtGG/Kradouque#1]
Merci

**Comment by YaourtGG** [comment]
Je travaille en environnement Microsoft, c'est non mdr

**Comment by Kocal** [comment]
J'ai dit "merci", donc tu le fais stppppppppppppppp xd

**Comment by YaourtGG** [comment]
Fait une PR et on verra si je l'accepte

**Comment by Kocal** [comment]
hihi
